# Generated by Django 5.1.7 on 2025-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('stock_quantity', models.FloatField(default=0)),
                ('cost_per_unit', models.FloatField(default=0)),
            ],
        ),
    ]
