# Generated by Django 5.1.7 on 2025-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('ml', 'mililiter')], max_length=2, null=True),
        ),
    ]
