# Generated by Django 5.1.7 on 2025-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('ml', 'mililiter'), ('pc', 'piece')], max_length=3, null=True),
        ),
    ]
