# Generated by Django 5.1.7 on 2025-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_type', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rosé'), ('sparkling', 'Sparkling')], default='red', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('stock_of_wine', models.IntegerField(default=0)),
                ('image_item', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
