# Generated by Django 5.1.7 on 2025-05-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuItemIngredients', '0001_initial'),
        ('menuItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuItems.menuitem'),
        ),
    ]
