# Generated by Django 5.1.7 on 2025-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_item',
            field=models.URLField(blank=True, null=True),
        ),
    ]
