# Generated by Django 5.1.7 on 2025-08-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_ceo_user_is_kitcher_user_is_waiter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ceo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_kitcher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_waiter',
        ),
    ]
