# Generated by Django 5.1.7 on 2025-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_ceo_remove_user_is_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='table_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
